[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_todo = "Ct2N3zw5LFiNj5mJ7hN2c4umze2pAWNjfYqazZHzDENy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mylinux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
